version: "3.8"
services:
  react:
    build:
      context: ./alina
    ports:
      - 3000:3000
    volumes:
      - ./alina:/app
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 4000 -w /data/src/FakeRestApi.json
    ports:
      - "4000:4000"
    volumes:
      - ./alina/src:/data/src
    restart: always
